# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import so_service_pb2 as so__service__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in so_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SalesOrderServiceStub:
    """───────────────────────────────────────────────────────────
    SO Fetch Service  — retrieve headers + line items from a
    previously processed (or direct-DB-looked-up) Sales Order.
    ───────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSalesOrder = channel.unary_unary(
                '/so_service.SalesOrderService/GetSalesOrder',
                request_serializer=so__service__pb2.SORequest.SerializeToString,
                response_deserializer=so__service__pb2.SOResponse.FromString,
                _registered_method=True)
        self.GetSOHeaders = channel.unary_unary(
                '/so_service.SalesOrderService/GetSOHeaders',
                request_serializer=so__service__pb2.HeadersRequest.SerializeToString,
                response_deserializer=so__service__pb2.HeadersResponse.FromString,
                _registered_method=True)


class SalesOrderServiceServicer:
    """───────────────────────────────────────────────────────────
    SO Fetch Service  — retrieve headers + line items from a
    previously processed (or direct-DB-looked-up) Sales Order.
    ───────────────────────────────────────────────────────────

    """

    def GetSalesOrder(self, request, context):
        """Returns the SO column headers and a list of line items
        for a given city, date, and SO format type.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSOHeaders(self, request, context):
        """Returns just the column headers (schema) for a given format.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SalesOrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSalesOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSalesOrder,
                    request_deserializer=so__service__pb2.SORequest.FromString,
                    response_serializer=so__service__pb2.SOResponse.SerializeToString,
            ),
            'GetSOHeaders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSOHeaders,
                    request_deserializer=so__service__pb2.HeadersRequest.FromString,
                    response_serializer=so__service__pb2.HeadersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'so_service.SalesOrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('so_service.SalesOrderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SalesOrderService:
    """───────────────────────────────────────────────────────────
    SO Fetch Service  — retrieve headers + line items from a
    previously processed (or direct-DB-looked-up) Sales Order.
    ───────────────────────────────────────────────────────────

    """

    @staticmethod
    def GetSalesOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/so_service.SalesOrderService/GetSalesOrder',
            so__service__pb2.SORequest.SerializeToString,
            so__service__pb2.SOResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSOHeaders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/so_service.SalesOrderService/GetSOHeaders',
            so__service__pb2.HeadersRequest.SerializeToString,
            so__service__pb2.HeadersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
